---
swagger: "2.0"
info:
  description: "API to interact with AppBrain."
  version: "2.0"
  title: "AppBrain API"
  contact:
    name: "AppBrain Support"
    email: "contact@appbrain.com"
host: "api.appbrain.com"
basePath: "/v2"
tags:
- name: "Information"
- name: "Promotion Campaigns"
schemes:
- "https"
paths:
  /info/getcountries:
    get:
      tags:
      - "Information"
      summary: "Countries information"
      description: "Returns a list of countries."
      operationId: "getCountries"
      produces:
      - "application/json"
      - "application/xml"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/CountryList"
  /info/getlibraries:
    get:
      tags:
      - "Information"
      summary: "Libraries information"
      description: "Returns a list of known libraries used in apps."
      operationId: "getLibraries"
      produces:
      - "application/json"
      - "application/xml"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/LibraryList"
  /info/getapp:
    get:
      tags:
      - "Information"
      summary: "App information"
      description: "Returns all information about an app. More information about usage\
        \ and charges is available at <a href='/info/help/api/pricing.html'>AppBrain\
        \ API pricing</a>."
      operationId: "getApp"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "package"
        in: "query"
        description: "package"
        required: true
        type: "string"
        x-exportParamName: "Package_"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/AppInfo"
        "400":
          description: "Invalid request"
        "401":
          description: "Unauthorized request"
        "429":
          description: "Too many requests"
      security:
      - apikey: []
  /campaigns/get:
    get:
      tags:
      - "Promotion Campaigns"
      summary: "Retrieves a promotion campaign"
      description: "Retrieves the details of a promotion campaign."
      operationId: "get"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "campaign"
        in: "query"
        description: "campaign"
        required: true
        type: "string"
        x-exportParamName: "Campaign"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PromotionCampaign"
        "400":
          description: "Invalid request"
        "401":
          description: "Unauthorized request"
        "429":
          description: "Too many requests"
      security:
      - apikey: []
  /campaigns/update:
    post:
      tags:
      - "Promotion Campaigns"
      summary: "Creates or updates a promotion campaign"
      description: "Creates a new promotion campaign or updates an existing one."
      operationId: "update"
      consumes:
      - "application/json"
      - "application/xml"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - in: "body"
        name: "body"
        description: "the properties of the campaign that must be updated"
        required: true
        schema:
          $ref: "#/definitions/PromotionCampaignUpdates"
        x-exportParamName: "Body"
      - name: "lowbidaction"
        in: "query"
        description: "what to do if a country bid is lower than the minimum allowed\
          \ bid (ERROR: throw an error, RAISE: raise the country bid, STOP: stop campaign\
          \ in the country)"
        required: false
        type: "string"
        enum:
        - "ERROR"
        - "RAISE"
        - "STOP"
        x-exportParamName: "Lowbidaction"
        x-optionalDataType: "String"
      responses:
        "200":
          description: "successful operation"
          schema:
            type: "string"
        "400":
          description: "Invalid request"
        "401":
          description: "Unauthorized request"
        "429":
          description: "Too many requests"
      security:
      - apikey: []
  /campaigns/list:
    get:
      tags:
      - "Promotion Campaigns"
      summary: "Lists all promotion campaigns"
      description: "Returns a list of identifiers of all promotion campaigns."
      operationId: "list"
      produces:
      - "application/json"
      - "application/xml"
      parameters: []
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/PromotionCampaignList"
        "400":
          description: "Invalid request"
        "401":
          description: "Unauthorized request"
        "429":
          description: "Too many requests"
      security:
      - apikey: []
  /info/browse:
    get:
      tags:
      - "Information"
      summary: "Apps information"
      description: "Returns a list of apps and everything about those apps. More information\
        \ about usage and charges is available at <a href='/info/help/api/pricing.html'>AppBrain\
        \ API pricing</a>."
      operationId: "browseApps"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "sort"
        in: "query"
        description: "sort order of the results (default: POPULAR)"
        required: false
        type: "string"
        enum:
        - "ALLTIME_DOWNLOADS"
        - "HOT-DAY"
        - "POPULAR_AUSTRALIA"
        - "POPULAR_BRAZIL"
        - "POPULAR_CANADA"
        - "POPULAR_DENMARK"
        - "POPULAR_FINLAND"
        - "POPULAR_FRANCE"
        - "POPULAR_GERMANY"
        - "POPULAR_HONGKONG"
        - "POPULAR_HUNGARY"
        - "POPULAR_INDIA"
        - "POPULAR_ITALY"
        - "POPULAR_JAPAN"
        - "POPULAR_KOREA"
        - "POPULAR_NETHERLANDS"
        - "POPULAR_NORWAY"
        - "POPULAR_POLAND"
        - "POPULAR_PORTUGAL"
        - "POPULAR_RUSSIA"
        - "POPULAR_SPAIN"
        - "POPULAR_SWEDEN"
        - "POPULAR_THAILAND"
        - "POPULAR_UK"
        - "POPULAR_USA"
        - "RATING"
        - "RECENT_DOWNLOADS"
        - "TIME"
        x-exportParamName: "Sort"
        x-optionalDataType: "String"
      - name: "filter"
        in: "query"
        description: "optional filter of the results"
        required: false
        type: "string"
        enum:
        - "FREE"
        - "NEW"
        - "PAID"
        - "PRICE_REDUCED"
        - "UPDATED"
        x-exportParamName: "Filter"
        x-optionalDataType: "String"
      - name: "category"
        in: "query"
        description: "optional filter for the Google Play category"
        required: false
        type: "string"
        enum:
        - "ACTION"
        - "ADVENTURE"
        - "ARCADE"
        - "ART_DESIGN"
        - "AUTO"
        - "BEAUTY"
        - "BOARD"
        - "BOOKS_REFERENCE"
        - "BUSINESS"
        - "CARD"
        - "CASINO"
        - "CASUAL"
        - "COMICS"
        - "COMMUNICATION"
        - "DATING"
        - "EDUCATION"
        - "EDUCATIONAL"
        - "ENTERTAINMENT"
        - "EVENTS"
        - "FINANCE"
        - "FOOD_DRINK"
        - "HEALTH_FITNESS"
        - "HOUSE_HOME"
        - "LIBRARIES_DEMO"
        - "LIFESTYLE"
        - "MEDIA_VIDEO"
        - "MEDICAL"
        - "MUSIC"
        - "MUSIC_AUDIO"
        - "NEWS_MAGAZINES"
        - "PARENTING"
        - "PERSONALIZATION"
        - "PHOTOGRAPHY"
        - "PRODUCTIVITY"
        - "PUZZLE"
        - "RACING"
        - "ROLE_PLAYING"
        - "SHOPPING"
        - "SIMULATION"
        - "SOCIAL"
        - "SPORTS"
        - "SPORTS_GAMES"
        - "STRATEGY"
        - "TOOLS"
        - "TRANSPORTATION"
        - "TRAVEL_LOCAL"
        - "TRIVIA"
        - "WEATHER"
        - "WORD"
        x-exportParamName: "Category"
        x-optionalDataType: "String"
      - name: "offset"
        in: "query"
        description: "offset of the browse results (default 0; max 500)"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "Offset"
        x-optionalDataType: "Int32"
      - name: "limit"
        in: "query"
        description: "number of the browse results (default 10; max 50)"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "Limit"
        x-optionalDataType: "Int32"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/AppInfoList"
        "400":
          description: "Invalid request"
        "401":
          description: "Unauthorized request"
        "429":
          description: "Too many requests"
      security:
      - apikey: []
  /info/search:
    get:
      tags:
      - "Information"
      summary: "Apps information"
      description: "Returns a list of apps and everything about those apps. More information\
        \ about usage and charges is available at <a href='/info/help/api/pricing.html'>AppBrain\
        \ API pricing</a>."
      operationId: "searchApps"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "query"
        in: "query"
        description: "search query"
        required: false
        type: "string"
        x-exportParamName: "Query"
        x-optionalDataType: "String"
      - name: "sort"
        in: "query"
        description: "sort order of the results (default: RELEVANCY)"
        required: false
        type: "string"
        enum:
        - "ALLTIME_DOWNLOADS"
        - "HOT-DAY"
        - "POPULAR_AUSTRALIA"
        - "POPULAR_BRAZIL"
        - "POPULAR_CANADA"
        - "POPULAR_DENMARK"
        - "POPULAR_FINLAND"
        - "POPULAR_FRANCE"
        - "POPULAR_GERMANY"
        - "POPULAR_HONGKONG"
        - "POPULAR_HUNGARY"
        - "POPULAR_INDIA"
        - "POPULAR_ITALY"
        - "POPULAR_JAPAN"
        - "POPULAR_KOREA"
        - "POPULAR_NETHERLANDS"
        - "POPULAR_NORWAY"
        - "POPULAR_POLAND"
        - "POPULAR_PORTUGAL"
        - "POPULAR_RUSSIA"
        - "POPULAR_SPAIN"
        - "POPULAR_SWEDEN"
        - "POPULAR_THAILAND"
        - "POPULAR_UK"
        - "POPULAR_USA"
        - "RATING"
        - "RECENT_DOWNLOADS"
        - "RELEVANCY"
        - "TIME"
        x-exportParamName: "Sort"
        x-optionalDataType: "String"
      - name: "filter"
        in: "query"
        description: "optional filter of the results"
        required: false
        type: "string"
        enum:
        - "FREE"
        - "NEW"
        - "PAID"
        - "PRICE_REDUCED"
        - "UPDATED"
        x-exportParamName: "Filter"
        x-optionalDataType: "String"
      - name: "category"
        in: "query"
        description: "optional filter for the Google Play category"
        required: false
        type: "string"
        enum:
        - "ACTION"
        - "ADVENTURE"
        - "ARCADE"
        - "ART_DESIGN"
        - "AUTO"
        - "BEAUTY"
        - "BOARD"
        - "BOOKS_REFERENCE"
        - "BUSINESS"
        - "CARD"
        - "CASINO"
        - "CASUAL"
        - "COMICS"
        - "COMMUNICATION"
        - "DATING"
        - "EDUCATION"
        - "EDUCATIONAL"
        - "ENTERTAINMENT"
        - "EVENTS"
        - "FINANCE"
        - "FOOD_DRINK"
        - "HEALTH_FITNESS"
        - "HOUSE_HOME"
        - "LIBRARIES_DEMO"
        - "LIFESTYLE"
        - "MEDIA_VIDEO"
        - "MEDICAL"
        - "MUSIC"
        - "MUSIC_AUDIO"
        - "NEWS_MAGAZINES"
        - "PARENTING"
        - "PERSONALIZATION"
        - "PHOTOGRAPHY"
        - "PRODUCTIVITY"
        - "PUZZLE"
        - "RACING"
        - "ROLE_PLAYING"
        - "SHOPPING"
        - "SIMULATION"
        - "SOCIAL"
        - "SPORTS"
        - "SPORTS_GAMES"
        - "STRATEGY"
        - "TOOLS"
        - "TRANSPORTATION"
        - "TRAVEL_LOCAL"
        - "TRIVIA"
        - "WEATHER"
        - "WORD"
        x-exportParamName: "Category"
        x-optionalDataType: "String"
      - name: "offset"
        in: "query"
        description: "offset of the browse results (default 0; max 500)"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "Offset"
        x-optionalDataType: "Int32"
      - name: "limit"
        in: "query"
        description: "number of the browse results (default 10; max 50)"
        required: false
        type: "integer"
        format: "int32"
        x-exportParamName: "Limit"
        x-optionalDataType: "Int32"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/AppInfoList"
        "400":
          description: "Invalid request"
        "401":
          description: "Unauthorized request"
        "429":
          description: "Too many requests"
      security:
      - apikey: []
securityDefinitions:
  apikey:
    description: "The API key for AppBrain API"
    type: "apiKey"
    name: "apikey"
    in: "query"
definitions:
  CountryInfo:
    type: "object"
    properties:
      code:
        type: "string"
        description: "country code"
      name:
        type: "string"
        description: "name of the country"
      minCpiBid:
        type: "number"
        format: "double"
        description: "minimum cost-per-install bid for app promotions in this country"
    description: "Information about a country"
    example:
      code: "code"
      name: "name"
      minCpiBid: 0.80082819046101150206595775671303272247314453125
  CountryList:
    type: "object"
    properties:
      countries:
        type: "array"
        xml:
          wrapped: true
        description: "country information"
        items:
          xml:
            name: "country"
          $ref: "#/definitions/CountryInfo"
    description: "List of countries"
    example:
      countries:
      - code: "code"
        name: "name"
        minCpiBid: 0.80082819046101150206595775671303272247314453125
      - code: "code"
        name: "name"
        minCpiBid: 0.80082819046101150206595775671303272247314453125
  Library:
    type: "object"
    properties:
      id:
        type: "string"
        description: "identifier for the library"
      name:
        type: "string"
        description: "name of the library"
      description:
        type: "string"
        description: "description of the library"
      types:
        type: "array"
        description: "types of the library"
        items:
          type: "string"
      tags:
        type: "array"
        description: "tags associated with the library"
        items:
          type: "string"
      officialUrl:
        type: "string"
        description: "official URL of the library"
      appBrainUrl:
        type: "string"
        description: "AppBrain URL of the library"
    description: "Information about a library"
    example:
      types:
      - "types"
      - "types"
      appBrainUrl: "appBrainUrl"
      name: "name"
      description: "description"
      id: "id"
      tags:
      - "tags"
      - "tags"
      officialUrl: "officialUrl"
  LibraryList:
    type: "object"
    properties:
      libraries:
        type: "array"
        xml:
          wrapped: true
        description: "library information"
        items:
          xml:
            name: "library"
          $ref: "#/definitions/Library"
    description: "List of known libraries"
    example:
      libraries:
      - types:
        - "types"
        - "types"
        appBrainUrl: "appBrainUrl"
        name: "name"
        description: "description"
        id: "id"
        tags:
        - "tags"
        - "tags"
        officialUrl: "officialUrl"
      - types:
        - "types"
        - "types"
        appBrainUrl: "appBrainUrl"
        name: "name"
        description: "description"
        id: "id"
        tags:
        - "tags"
        - "tags"
        officialUrl: "officialUrl"
  AppInfo:
    type: "object"
    properties:
      package:
        type: "string"
        description: "package"
      versionString:
        type: "string"
        description: "most recent version"
      versionCode:
        type: "integer"
        format: "int32"
        description: "most recent version code"
      name:
        type: "string"
        description: "name of the app"
      shortDescription:
        type: "string"
        description: "short one-line description of the app"
      description:
        type: "string"
        description: "description of the app"
      marketCategory:
        type: "string"
        description: "market category of the app"
      price:
        type: "string"
        description: "price of the app"
      apkSize:
        type: "integer"
        format: "int64"
        description: "size of the APK"
      maturityLevel:
        type: "string"
        description: "maturity level of the app"
        enum:
        - "EVERYONE"
        - "LOW"
        - "MEDIUM"
        - "HIGH"
      minSdkVersion:
        type: "integer"
        format: "int32"
        description: "minimum supported SDK version"
      maxSdkVersion:
        type: "integer"
        format: "int32"
        description: "maximum supported SDK version"
      supportsApp2SD:
        type: "string"
        description: "whether the app can be installed on external storage"
        enum:
        - "TRUE"
        - "FALSE"
      launchTime:
        type: "integer"
        format: "int32"
        description: "timestamp of the app's launch in seconds since epoch"
      lastAppUpdateTime:
        type: "integer"
        format: "int32"
        description: "timestamp of the app's latest update in seconds since epoch"
      infoRefreshTime:
        type: "integer"
        format: "int32"
        description: "timestamp of the last refresh of the app information in seconds\
          \ since epoch"
      downloadsCategory:
        type: "string"
        description: "Google play category of the number of downloads"
      estimatedDownloads:
        type: "integer"
        format: "int64"
        description: "estimated number of downloads"
      estimatedRecentDownloads:
        type: "integer"
        format: "int64"
        description: "estimated number of downloads in the last 30 days"
      rating:
        type: "number"
        format: "double"
        description: "average rating"
      recentRating:
        type: "number"
        format: "double"
        description: "average rating in the last 30 days"
      ratingCount:
        type: "integer"
        format: "int32"
        description: "number of ratings"
      rating1StarCount:
        type: "integer"
        format: "int32"
        description: "number of 1-star ratings"
      rating2StarCount:
        type: "integer"
        format: "int32"
        description: "number of 2-star ratings"
      rating3StarCount:
        type: "integer"
        format: "int32"
        description: "number of 3-star ratings"
      rating4StarCount:
        type: "integer"
        format: "int32"
        description: "number of 4-star ratings"
      rating5StarCount:
        type: "integer"
        format: "int32"
        description: "number of 5-star ratings"
      plusOneCount:
        type: "integer"
        format: "int32"
        description: "number of +1s"
      commentCount:
        type: "integer"
        format: "int32"
        description: "number of comments"
      iconUrl:
        type: "string"
        description: "URL of the app's icon"
      featureGraphicUrl:
        type: "string"
        description: "URL of the app's feature graphic"
      youtubeUrl:
        type: "string"
        description: "YouTube URL of the app's promo video"
      developerName:
        type: "string"
        description: "name of the developer of the app"
      developerEmail:
        type: "string"
        description: "email address of the developer"
      developerAddress:
        type: "string"
        description: "address of the developer"
      website:
        type: "string"
        description: "official website of the app"
      screenshotUrls:
        type: "array"
        xml:
          wrapped: true
        description: "URLs of the app's screenshots"
        items:
          type: "string"
          xml:
            name: "screenshotUrl"
      permissions:
        type: "array"
        xml:
          wrapped: true
        description: "requested permissions"
        items:
          type: "string"
          xml:
            name: "permission"
      libraries:
        type: "array"
        xml:
          wrapped: true
        description: "libraries used in the app"
        items:
          type: "string"
          xml:
            name: "library"
    description: "Everything about an app"
    example:
      developerAddress: "developerAddress"
      rating5StarCount: 7
      screenshotUrls:
      - "screenshotUrls"
      - "screenshotUrls"
      marketCategory: "marketCategory"
      infoRefreshTime: 7
      rating: 2.027123023002321833274663731572218239307403564453125
      description: "description"
      developerEmail: "developerEmail"
      rating2StarCount: 1
      recentRating: 4.1456080298839363962315474054776132106781005859375
      price: "price"
      youtubeUrl: "youtubeUrl"
      permissions:
      - "permissions"
      - "permissions"
      rating1StarCount: 1
      featureGraphicUrl: "featureGraphicUrl"
      apkSize: 6
      iconUrl: "iconUrl"
      rating4StarCount: 6
      developerName: "developerName"
      maxSdkVersion: 5
      website: "website"
      package: "package"
      versionString: "versionString"
      estimatedRecentDownloads: 3
      libraries:
      - "libraries"
      - "libraries"
      plusOneCount: 1
      shortDescription: "shortDescription"
      downloadsCategory: "downloadsCategory"
      ratingCount: 7
      estimatedDownloads: 9
      versionCode: 0
      commentCount: 4
      minSdkVersion: 1
      launchTime: 5
      rating3StarCount: 1
      name: "name"
      maturityLevel: "EVERYONE"
      lastAppUpdateTime: 2
      supportsApp2SD: "TRUE"
  Country:
    type: "object"
    properties:
      code:
        type: "string"
        description: "the two-letter ISO country code"
      cpi:
        type: "number"
        format: "double"
        description: "the maximum cost-per-install for a country in dollars"
    description: "Settings for a country in the promotion campaign"
    example:
      code: "code"
      cpi: 1.46581298050294517310021547018550336360931396484375
  PromotionCampaign:
    type: "object"
    properties:
      campaign:
        type: "string"
        description: "identifier of the promotion campaign"
      state:
        type: "string"
        description: "state of the promotion campaign"
      name:
        type: "string"
        description: "name/description of the promotion campaign"
      title:
        type: "string"
        description: "promotion title of the promotion campaign"
      subtitle:
        type: "string"
        description: "promotion subtitle of the promotion campaign"
      dailyBudget:
        type: "number"
        format: "double"
        description: "daily budget of the promotion campaign in dollars"
      remainingBudget:
        type: "number"
        format: "double"
        description: "total remaining budget the promotion campaign in dollars"
      installTracking:
        type: "string"
        description: "attribution partner that is used for install tracking"
        enum:
        - "APPBRAIN"
        - "ADJUST"
        - "APPSFLYER"
        - "SINGULAR"
        - "KOCHAVA"
        - "TUNE"
      clickthroughUrl:
        type: "string"
        description: "clickthrough URL of the promotion campaign"
      countries:
        type: "array"
        xml:
          wrapped: true
        description: "list of settings for each country where the campaign is running"
        items:
          xml:
            name: "country"
          $ref: "#/definitions/Country"
      allowedSubIds:
        type: "array"
        xml:
          wrapped: true
        description: "list of publisher subIDs to allow for this campaign"
        items:
          type: "string"
          xml:
            name: "allowedSubId"
      blockedSubIds:
        type: "array"
        xml:
          wrapped: true
        description: "list of publisher subIDs to block for this campaign"
        items:
          type: "string"
          xml:
            name: "blockedSubId"
    description: "All details of a promotion campaign"
    example:
      allowedSubIds:
      - "allowedSubIds"
      - "allowedSubIds"
      clickthroughUrl: "clickthroughUrl"
      remainingBudget: 6.02745618307040320615897144307382404804229736328125
      dailyBudget: 0.80082819046101150206595775671303272247314453125
      subtitle: "subtitle"
      name: "name"
      campaign: "campaign"
      state: "state"
      countries:
      - code: "code"
        cpi: 1.46581298050294517310021547018550336360931396484375
      - code: "code"
        cpi: 1.46581298050294517310021547018550336360931396484375
      title: "title"
      installTracking: "APPBRAIN"
      blockedSubIds:
      - "blockedSubIds"
      - "blockedSubIds"
  PromotionCampaignUpdates:
    type: "object"
    required:
    - "campaign"
    properties:
      campaign:
        type: "string"
        description: "identifier of the promotion campaign (i.e. the package of the\
          \ promoted app, eventually followed by a dash and an index for multiple\
          \ campaigns per app.)"
      state:
        type: "string"
        description: "state of the promotion campaign"
        enum:
        - "RUNNING"
        - "STOPPED"
      name:
        type: "string"
        description: "name/description of the promotion campaign"
      title:
        type: "string"
        description: "promotion title of the promotion campaign"
      subtitle:
        type: "string"
        description: "promotion subtitle of the promotion campaign"
      dailyBudget:
        type: "number"
        format: "double"
        description: "daily budget of the promotion campaign in dollars (a negative\
          \ value indicates no budget limit)"
      remainingBudget:
        type: "number"
        format: "double"
        description: "total remaining budget the promotion campaign in dollars (a\
          \ negative value indicates no budget limit)"
      installTracking:
        type: "string"
        description: "attribution partner that is used for install tracking"
        enum:
        - "APPBRAIN"
        - "ADJUST"
        - "APPSFLYER"
        - "SINGULAR"
        - "KOCHAVA"
        - "TUNE"
      clickthroughUrl:
        type: "string"
        description: "clickthrough URL of the promotion campaign"
      countries:
        type: "array"
        xml:
          wrapped: true
        description: "list of settings for each country where the campaign is running;\
          \ setting this list overwrites all country settings for the promotion campaign\
          \ (can't be used simultaneously with updateCountries or removeCountries)"
        items:
          xml:
            name: "country"
          $ref: "#/definitions/Country"
      updateCountries:
        type: "array"
        xml:
          wrapped: true
        description: "updates the provided settings for the countries (can't be used\
          \ simultaneously with countries)"
        items:
          xml:
            name: "updateCountry"
          $ref: "#/definitions/Country"
      removeCountries:
        type: "array"
        xml:
          wrapped: true
        description: "removes the provided countries from the promotion campaign (can't\
          \ be used simultaneously with countries)"
        items:
          type: "string"
          xml:
            name: "removeCountry"
      allowedSubIds:
        type: "array"
        xml:
          wrapped: true
        description: "list of publisher subIDs to allow for this campaign; setting\
          \ this list overwrites all existing allowed subIDs (can't be used simultaneously\
          \ with addAllowedSubIds)"
        items:
          type: "string"
          xml:
            name: "allowedSubId"
      addAllowedSubIds:
        type: "array"
        xml:
          wrapped: true
        description: "adds publisher subIDs to the list of allowed subIDs (can't be\
          \ used simultaneously with allowedSubIds)"
        items:
          type: "string"
          xml:
            name: "addAllowedSubId"
      blockedSubIds:
        type: "array"
        xml:
          wrapped: true
        description: "list of publisher subIDs to block for this campaign; setting\
          \ this list overwrites all existing blocked subIDs (can't be used simultaneously\
          \ with addBlockedSubIds)"
        items:
          type: "string"
          xml:
            name: "blockedSubId"
      addBlockedSubIds:
        type: "array"
        xml:
          wrapped: true
        description: "adds publisher subIDs to the list of blocked subIDs (can't be\
          \ used simultaneously with blockedSubIds)"
        items:
          type: "string"
          xml:
            name: "addBlockedSubId"
    description: "Updates for a promotion campaign"
    example:
      allowedSubIds:
      - "allowedSubIds"
      - "allowedSubIds"
      addAllowedSubIds:
      - "addAllowedSubIds"
      - "addAllowedSubIds"
      remainingBudget: 6.02745618307040320615897144307382404804229736328125
      addBlockedSubIds:
      - "addBlockedSubIds"
      - "addBlockedSubIds"
      countries:
      - code: "code"
        cpi: 1.46581298050294517310021547018550336360931396484375
      - code: "code"
        cpi: 1.46581298050294517310021547018550336360931396484375
      title: "title"
      removeCountries:
      - "removeCountries"
      - "removeCountries"
      installTracking: "APPBRAIN"
      blockedSubIds:
      - "blockedSubIds"
      - "blockedSubIds"
      clickthroughUrl: "clickthroughUrl"
      updateCountries:
      - code: "code"
        cpi: 1.46581298050294517310021547018550336360931396484375
      - code: "code"
        cpi: 1.46581298050294517310021547018550336360931396484375
      dailyBudget: 0.80082819046101150206595775671303272247314453125
      subtitle: "subtitle"
      name: "name"
      campaign: "campaign"
      state: "RUNNING"
  PromotionCampaignList:
    type: "object"
    properties:
      campaigns:
        type: "array"
        xml:
          wrapped: true
        description: "identifiers of existing promotion campaigns"
        items:
          type: "string"
          xml:
            name: "campaign"
    description: "List of promotion campaigns"
    example:
      campaigns:
      - "campaigns"
      - "campaigns"
  AppInfoList:
    type: "object"
    properties:
      apps:
        type: "array"
        xml:
          wrapped: true
        description: "List of apps"
        items:
          xml:
            name: "app"
          $ref: "#/definitions/AppInfo"
    description: "List of apps"
    example:
      apps:
      - developerAddress: "developerAddress"
        rating5StarCount: 7
        screenshotUrls:
        - "screenshotUrls"
        - "screenshotUrls"
        marketCategory: "marketCategory"
        infoRefreshTime: 7
        rating: 2.027123023002321833274663731572218239307403564453125
        description: "description"
        developerEmail: "developerEmail"
        rating2StarCount: 1
        recentRating: 4.1456080298839363962315474054776132106781005859375
        price: "price"
        youtubeUrl: "youtubeUrl"
        permissions:
        - "permissions"
        - "permissions"
        rating1StarCount: 1
        featureGraphicUrl: "featureGraphicUrl"
        apkSize: 6
        iconUrl: "iconUrl"
        rating4StarCount: 6
        developerName: "developerName"
        maxSdkVersion: 5
        website: "website"
        package: "package"
        versionString: "versionString"
        estimatedRecentDownloads: 3
        libraries:
        - "libraries"
        - "libraries"
        plusOneCount: 1
        shortDescription: "shortDescription"
        downloadsCategory: "downloadsCategory"
        ratingCount: 7
        estimatedDownloads: 9
        versionCode: 0
        commentCount: 4
        minSdkVersion: 1
        launchTime: 5
        rating3StarCount: 1
        name: "name"
        maturityLevel: "EVERYONE"
        lastAppUpdateTime: 2
        supportsApp2SD: "TRUE"
      - developerAddress: "developerAddress"
        rating5StarCount: 7
        screenshotUrls:
        - "screenshotUrls"
        - "screenshotUrls"
        marketCategory: "marketCategory"
        infoRefreshTime: 7
        rating: 2.027123023002321833274663731572218239307403564453125
        description: "description"
        developerEmail: "developerEmail"
        rating2StarCount: 1
        recentRating: 4.1456080298839363962315474054776132106781005859375
        price: "price"
        youtubeUrl: "youtubeUrl"
        permissions:
        - "permissions"
        - "permissions"
        rating1StarCount: 1
        featureGraphicUrl: "featureGraphicUrl"
        apkSize: 6
        iconUrl: "iconUrl"
        rating4StarCount: 6
        developerName: "developerName"
        maxSdkVersion: 5
        website: "website"
        package: "package"
        versionString: "versionString"
        estimatedRecentDownloads: 3
        libraries:
        - "libraries"
        - "libraries"
        plusOneCount: 1
        shortDescription: "shortDescription"
        downloadsCategory: "downloadsCategory"
        ratingCount: 7
        estimatedDownloads: 9
        versionCode: 0
        commentCount: 4
        minSdkVersion: 1
        launchTime: 5
        rating3StarCount: 1
        name: "name"
        maturityLevel: "EVERYONE"
        lastAppUpdateTime: 2
        supportsApp2SD: "TRUE"
externalDocs:
  description: "AppBrain API Documentation"
  url: "https://www.appbrain.com/info/help/api/specification.html"
